### ISSUE TITLE
Guard Endpoint with Role from API

### ISSUE THREAD

**Issue by ryuuzake** [agustinanisaf/SquareCheck-frontend#32]
Functionality
---
- [x] pengecekan agar user dengan role `student` tidak dapat masuk ke layanan web

Idea
---
- [x] pengecekan login ditambahkan pengecekan role dari `/auth/me`

**Comment by ryuuzake** [comment]
@rizabach29 pls elp with this 😢

**Comment by rizabach29** [comment]
Iyoo iki aku ga mudeng kok gaisok, pertama kali tak gawe sek isok

**Comment by ryuuzake** [comment]
gak isok yo opo bach?
