### ISSUE TITLE
dockerize project

### ISSUE THREAD

**Issue by rizabach29** [agustinanisaf/SquareCheck-frontend#53]

**Comment by rizabach29** [comment]
@ryuuzake tulung di cek fis

**Comment by ryuuzake** [comment]
Lek nak kene pake port 80 ae dalem e

https://mherman.org/blog/dockerizing-a-react-app/

**Comment by ryuuzake** [comment]
@rizabach29 pull request sek yo ben isok direview

**Comment by rizabach29** [comment]
Okeoke, ngeset env ne yaopo sek salah iku commit e

**Comment by ryuuzake** [comment]
ngeset e atek .env.production ketok e. Iku engkok nak ansible e ae sing ngatur soale IPne kan entuk e teko kono pas deploy nak server

References
https://create-react-app.dev/docs/adding-custom-environment-variables
